AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Convert src files to MP3
Parameters:
  BucketName:
    Description: Name of S3 bucket
    Type: String
Resources:
  AudioHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 300
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
              Resource: 'arn:aws:s3:::*'
            - Effect: Allow
              Action:
                - 'transcribe:StartTranscriptionJob'
              Resource: '*'
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket
            Events: s3:ObjectCreated:*

  ImageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
